### ISSUE TITLE
Allow user to override less compiler by manually installing preferred version.

### ISSUE THREAD

**Issue by macrosblackd** [gruntjs/grunt-contrib-less#164]
It would be nice to be able to use a specific version of less, similar to the way grunt-ts allows the user to use a specific version of typescript.

Use-Case:
The project I am currently working on is stuck using less 1.3.3. I am currently working to integrate grunt into our workflow and am unable to upgrade our dependencies.

**Comment by ddprrt** [comment]
Implementing this in the plugin would actually be a challenge, since there's a huge API gap in LESS between 1.x and 2.x, the latter which is currently used by `grunt-contrib-less`. 

However, If you don't rely on CI/CD (which you should), you can already achieve swapping versions. First, install a `grunt-contrib-less` version which still uses 1.x, I tried it with version 0.10. Also install the desired LESS version

```
npm install --save-dev grunt-contrib-less@0.10.0 less@1.3.3
```

Then delete the installed dependency of grunt-contrib-less:

```
rm -rf node_modules/grunt-contrib-less/node_modules/less
```

According to the [http://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders](Node.js) docs `grunt-contrib-less` will look for LESS one directory upwards.

**Comment by sindresorhus** [comment]
What @ddprrt said.
