### ISSUE TITLE
about the  plugins

### ISSUE THREAD

**Issue by ray0324** [gruntjs/grunt-contrib-less#233]
production: {
                options: {
                    paths: ["./"],
                    plugins: [
                        new require('less-plugin-autoprefix')({
                            browsers: ["last 2 versions"]
                        }),
                        new require('less-plugin-clean-css')({advanced: true})
                    ]
                },
                files: {
                    "css/metro.css": "less/metro.less"
                }
            }

 
![01](https://cloud.githubusercontent.com/assets/5204198/5534114/1a73451a-8a93-11e4-967d-444f9c7339f8.jpg)

less-plugin-autoprefix  less-plugin-clean-css  seems not work

**Comment by neogic** [comment]
I think I'm seeing the same issue with plugins not taking effect. I have 'grunt-contrib-less' v1.1.0 installed locally to a project, all other modules installed locally and up-to-date. "Gruntfile.js" includes the following LESS config entry:

    less: {
      dist: {
        files: {
          '<%= yeoman.app %>/styles/main.css': ['<%= yeoman.app %>/styles/main.less']
        },
        options: {
          plugins: [
            new (require('less-plugin-autoprefix'))({browsers: ["last 2 versions"]})
          ],
          sourceMap: true,
          sourceMapFilename: '<%= yeoman.app %>/styles/main.css.map',
        }
      }
    },

When I run "grunt less --verbose", the LESS task completes as normal but autoprefix hasn't had any effect (on a file that is normally definitely affected by it). The only mention of the plugin in the verbose output is:

    Options: report="min", banner="", plugins=[{"options":{"browsers":["last 2 versions"]},"minVersion":[2,0,0]}], ...".

I've also tried without plugin parameters line - no difference:

          plugins: [
            require('less-plugin-autoprefix')
          ],

If I change the plugin require name to something bogus, it correctly throws an error - which seems to suggest the plugin is being found, it's just not taking effect.

I'm about to give up on 'grunt-contrib-less' plugins and resort to separate tasks, but perhaps you can help Luke? Many thanks in advance - and thank you for the great plugin!

**Comment by rindybo** [comment]
you can try this
var autoprefix  =  require('less-plugin-autoprefix');
var autoprefixPlugin =  autoprefix ({browsers: ["last 2 versions"]});

plugins: [ autoprefixPlugin ]

**Comment by neogic** [comment]
Really appreciate the quick reply Luke, thank you :)  OK, firstly the above was written after a long day, so you hopefully worked out "v1.1.0" refers to the 'less-plugin-autoprefix' version, whereas 'grunt-contrib-less' is v1.0.0. [UPDATE - see below - this is a lie :) ]

I tried changing to "last 20 versions", but still no change (I made a test change to the .less file to ensure regenerated). I also tried rindybo's kind suggestion (with assign code at top), but no change (and --verbose shows `plugins=[null]`).

If I run "lessc" directly instead of via grunt, it works perfectly (adding tons of rules, removing some existing unneeded prefixes):

    lessc "app\styles\main.less" "app\styles\main.css" --autoprefix="last 2 versions"

**AH HA!** OK - oh dear, shoot me. It seems the latest version of 'generator-bootstrap-less' (v3.2.1) has in its package.json: `"grunt-contrib-less": "^0.11.4"`.

Which means - you guessed it - I actually had v0.11.4 installed for this project, as "^" prevents upgrading to a higher major version (which I guess it considers v0.12.x to be? but certainly v1.0.0) during a "npm update". 

My confusion (even at the start of this post) was because `npm show grunt-contrib-less` shows `version: '1.0.0'` - but this doesn't actually show the installed version!  In actual fact, to check the installed version you must run `npm list grunt-contrib-less` (or for all modules: `npm list --depth=0`). How very confusing!

Strongest apologies Luke - thank you so much for your help!  Ben

**Comment by janbaer** [comment]
I've the same problem. I tried to integrate the autoprefix-plugin, but it did nothing. I also tried the tip from @rindybo, but it hasn't helped.

This is the autoput when I'm starting grunt with the **--verbose** option

```
Running "less:development" (less) task
Verifying property less.development exists in config...OK
Files: public/css/styles.less -> public/css/styles.css
Options: banner="", sourceMap=false
Reading public/css/styles.less...OK
Writing public/css/styles.css...OK
File public/css/styles.css created
```

I've installed the latest versions of both components.
